### ISSUE TITLE
CadHub

### ISSUE THREAD

**Issue by Irev-Dev** [garyhodgson/openscad.net#17]
Hey @garyhodgson,

Just thought I'd give you an FYI that I'm working on a web version of OpenSCAD. Partly just wanted to let you know, but of course love any feedback you may have since you have experience here.

It's very much WIP, but there's a preview available at https://cadhub.xyz/dev-ide
Or there's a video here https://imgur.com/a/NlxILTW

One quick bit of information is I'm not forking openscad, I'm just running it server-side with the cli. There were a couple of reason I chose this as the integration path, but one of them was making it easy to upgrade to newer version of OpenSCAD.

I'm curious why did you stop maintaining openscad.net? just ran out of steam? or was keeping up with OpenSCAD proving to be too much work.

Kind regards,
Kurt

**Comment by garyhodgson** [comment]
Hey Kurt, sounds like a neat project! 

openscad.net was mainly an experiment to see how much could actually be achieved in the browser.  The project anguished a bit mainly due to lack of time more than anything, and recently I haven't been doing much 3D printer stuff at all.

Best of luck with Cadhub!

Cheeers,
Gary
